#!/bin/bash
set -euo pipefail

function prepare_dirs {
   mkdir -p "$HOME/.llama.cpp/models"
}

function install_models_ini {
    local source_models_ini="$(dirname "$0")/configs/models.ini"
    local target_models_ini="$HOME/.llama.cpp/models.ini"
    local full_models_path="$HOME/.llama.cpp/models"

    # Create or update the models.ini file
    cp -u "$source_models_ini" "$target_models_ini"
  
    # Replace the placeholder with the actual path
    sed -i "s|TARGET_PATH|$full_models_path|g" "$target_models_ini"

    echo "Config file '$target_models_ini' patched with absolute paths."
}

function install_packages() {
    makepkg -sic
}

function main {

    prepare_dirs

    if [[ "$1" == "config" ]]; then
        install_models_ini
    else
        install_packages
        install_models_ini
    fi
}   


main "$@"
