#!/bin/bash

function prepare_dirs {
   declare models_path="$HOME/.llama.cpp/models"
   mkdir -p "$models_path"
}

function install_config() {
    declare -A config_files=(
        ["models.ini"]="$HOME/.llama.cpp/models.ini"
    )

    for config_file in "${!config_files[@]}"; do
        local target_path="${config_files[$config_file]}"
        cp -u "$(dirname "$0")/configs/$config_file" "$target_path"
        echo "Config file '$target_path' installed/updated."
    done
}


function install_packages() {
    makepkg -sic
}

function main {

    prepare_dirs

    if [[ "$1" == "config" ]]; then
        install_config
    else
        install_packages
        install_config
    fi
}   


main "$@"
