#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../common
source "${SCRIPT_DIR}/../common"

PACKAGE_NAME="visual-studio-code"
PKG_DIR="$(cd "${SCRIPT_DIR}/../../visual-studio-code" && pwd)"
PKGBUILD="${PKG_DIR}/PKGBUILD"

function install() {
    install_pkg_if_needed "$PACKAGE_NAME" "$PKGBUILD" -sic
}

function main {
    install
    reset_git
}

main "$@"
