; Global llama-server preset template.
; During install, TARGET_PATH is replaced with your absolute model directory.

version = 1

[*]
jinja = true
flash-attn = on
mmap = false

[Qwen3.6-35B-A3B-UD-IQ4_NL]
model = TARGET_PATH/Qwen3.6-35B-A3B-UD-IQ4_NL.gguf
ctx-size = 120000
n-gpu-layers = 99
threads = 6
threads-batch = 6

temp = 0.5
top-p = 0.95
top-k = 20
min-p = 0.0
reasoning = on

chat-template-kwargs = {"preserve_thinking": true}


[Qwen3.6-35B-A3B-MTP-UD-IQ4_NL]
model = TARGET_PATH/Qwen3.6-35B-A3B-MTP-UD-IQ4_NL.gguf
ctx-size = 120000
n-gpu-layers = 99
threads = 6
threads-batch = 6

spec-type = draft-mtp 
spec-draft-n-max = 3

temp = 0.4
top-p = 0.95
top-k = 20
min-p = 0.0
reasoning = on

chat-template-kwargs = {"preserve_thinking": true}


[gemma-4-26B-A4B-it-UD-IQ4_NL]
model = TARGET_PATH/gemma-4-26B-A4B-it-UD-IQ4_NL.gguf
ctx-size = 120000
n-gpu-layers = 99
threads = 6
threads-batch = 6

temp = 1.0
top-p = 0.95
top-k = 64

reasoning = on

chat-template-kwargs = {"preserve_thinking": true}
